version: '3.7'
services:
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin@admin
    ports:
      - 9000:9000
      - 9001:9001
    command: 
      - server
      - home/shared
      - --console-address
      - :9001
